name: mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  jwt_decoder: ^2.0.1
  provider: ^6.0.5
  intl: ^0.18.0
  google_nav_bar: ^5.0.6
  flutter_secure_storage: ^8.0.0
  collection: ^1.17.1
  flutter_slidable: ^2.0.0
  image_picker: ^0.8.7
  url_launcher: ^6.1.10
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
